import type { Metadata } from "next";
import { Aboreto, Afacad } from "next/font/google";
import "./globals.css";

const aboretoFont = Aboreto({
  weight: '400',
  variable: '--font-aboreto',
  subsets: ["latin"],
});

const afacadFont = Afacad({
  weight: '400',
  variable: '--font-afacad',  // ✅ Fixed spelling
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aboretoFont.variable} ${afacadFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}